### ISSUE TITLE
user settings and snippets are still created in "%appdata%/code"

### ISSUE THREAD

**Issue by dewdad** [garethflowers/vscode-portable#12]
I'm running on windows. And when I open the user settings.json from the quickbar it create a new one in the non-portable location, "%appdata%/code".

**Comment by thdoan** [comment]
When you close the app, the settings are copied to the portable folder and `%appdata%/code` is removed completely. At least it does for me (v1.3.1).

**Comment by garethflowers** [comment]
This should now be resolved in [v1.6](https://github.com/garethflowers/vscode-portable/releases/tag/v1.6) - now that issues Microsoft/vscode#8990 and Microsoft/vscode#12129 have been resolved.

**Comment by davidtaylorjr** [comment]
@garethflowers This is working properly and the issue can be closed.

The software successfully creates a data folder inside the package contents for the portable app. This also makes updates easier as you just copy the data folder into the update.

**Comment by stla** [comment]
I'm using `v.1.10.1` and I have the same issue. VSCode has also installed an extension in `%USERPROFILE%/.vscode`. Is there a way to change that?
