### ISSUE TITLE
New Version 1.7 - 1.7.1 (October 2016)

### ISSUE THREAD

**Issue by MisterX2000** [garethflowers/vscode-portable#15]
There is a new version available,
version 1.7 with the 1.7.1 Recovery Build.

Changelog: https://code.visualstudio.com/Updates

Would be very thankful for an update.

**Comment by garethflowers** [comment]
I'll try and get this done soon.

**Comment by garethflowers** [comment]
[v1.7.1](https://github.com/garethflowers/vscode-portable/releases/tag/v1.7.1) now released!

**Comment by Enamex** [comment]
There's an error about not finding "App/VSCode/code.exe" or something like that.
