### ISSUE TITLE
Integration w/ GitPortable

### ISSUE THREAD

**Issue by shnbwmn** [garethflowers/vscode-portable#16]
_Hi there_

**Git** has to be installed to use it within VSCode, however there is [**GitPortable**](https://github.com/sheabunge/GitPortable) available within PA format.

Would it be possible to let _VSCodePortable_ use _GitPortable_?

**Comment by tschertel** [comment]
There is also a portable version of git on official git page.
See: https://git-scm.com/download/win

**Comment by shnbwmn** [comment]
GitPortable actually uses the official 7z distribution. The official thumbdrive edition still saves `.gitconfig` and `.bash_history` to the user directory.

**Comment by garethflowers** [comment]
To get it working you should just be able to configure the `git.path` option within User Settings in Visual Studio Code to point to the Git.exe binary within GitPortable.

To keep it portable you will probably want to go with a relative path..
```
"git.path": "../../gitportable/app/git/bin/git.exe"
```

**Comment by shnbwmn** [comment]
Thanks! Totally overlooked that particular option.
