### ISSUE TITLE
Need process to upgrade from previous versions

### ISSUE THREAD

**Issue by jahshuah** [garethflowers/vscode-portable#17]
Upgrading from a previous version by simply overwriting the portable app blows away user configurations (extensions, configuration settings, etc.). Any way you could post instructions for salvaging user configurations while upgrading to new versions?

Thanks,
Josh

**Comment by jahshuah** [comment]
Nevermind. Extracting the .zip doesn't wipe out user configurations. Not sure what I did before; must have been a bonehead mistake ;)

**Comment by RoyiAvital** [comment]
I hope the portable version is coming with all the telemetry and update mechanism disabled.

Is it?
