### ISSUE TITLE
Orphaned Code.exe processes 

### ISSUE THREAD

**Issue by ghost** [garethflowers/vscode-portable#20]
Thank you for an excellent and most valuable project.
I'm seeing one issue: After closing VS code there are up to four orphaned Code.exe processes running in the background consuming RAM, and when VS code is opened again and then closed minutes later, there are then more orphaned Code.exe processes, as seen in Task Manager, and free RAM gets consumed, possibly crashing the computer. This is a Windows 10, 64 bit machine.

**Comment by garethflowers** [comment]
This kind of problem is usually caused by an extension. Try disabling all extensions in VSCode and retrying.
