### ISSUE TITLE
Visual Studio Code Portable cannot be started

### ISSUE THREAD

**Issue by KeplerIO** [garethflowers/vscode-portable#22]
I downloaded the zip file straight from this page and unpacked it. Tried to start it up. Was greeted with:

![2017-03-24_10-24-28](https://cloud.githubusercontent.com/assets/26471970/24306022/40efce86-107c-11e7-91bd-584de867be74.png)

Nice app bro

**Comment by tschertel** [comment]
No offense, but did you miss "could not be found"??
You need to download VSC zip package from
https://code.visualstudio.com/Download



--
Tomás Schertel

**Comment by garethflowers** [comment]
You should download from the [Releases](https://github.com/garethflowers/vscode-portable/releases) section - at the top of the main page.

If you download using the 'Clone or download' button then you are just getting the source code. You would then need to download the binaries manually - just as @tschertel described.
