### ISSUE TITLE
File path too long when extracting

### ISSUE THREAD

**Issue by DanielHernandez** [garethflowers/vscode-portable#3]
![issue1](https://cloud.githubusercontent.com/assets/857649/13916230/c38def36-ef2f-11e5-9145-a01695dc10df.PNG)
![issue2](https://cloud.githubusercontent.com/assets/857649/13916229/c38958e0-ef2f-11e5-8127-45d27e984a5d.PNG)

Still attempted to run it, but it cannot run because of privileges. This is definitely an issue with my computer at work unfortunately. 

![issue3](https://cloud.githubusercontent.com/assets/857649/13916308/361ffa80-ef30-11e5-851c-7b820763f243.PNG)

**Comment by garethflowers** [comment]
This is a know problem at the moment. It's due to the number of nested modules that is used by Node inside the applicaiton.

The current workaround is too install/extract the application in to a location with a short a path as possible (i.e. in `C:\`).

I'm currently investigating a fix.

**Comment by Chaz6** [comment]
I have this problem too. This exposes one of npm's shortcomings.

**Comment by Luminess** [comment]
@Chaz6 That version is not truely portable. It's literally just what the installer installs zipped up. The issue for VSCode portability is tracked [here](https://github.com/Microsoft/vscode/issues/329).

**Comment by maybeec** [comment]
Have you tried to extract it with 7z with "extract here..." command?
Basically, whenever you choose "extract To" the explorer API will be used for copying, which leads to the long path issue. Otherwise, e.g. 7z circumvents the explorer API as well as several other tools as the file system of windows allows even longer paths.

**Comment by vKepler** [comment]
Literally F2 and rename the file something shorter......

**Comment by garethflowers** [comment]
Path length has been reduced in recent versions of Visual Studio Code, so this should take care of this problem.
