### ISSUE TITLE
folder name with "#"

### ISSUE THREAD

**Issue by alekk84** [garethflowers/vscode-portable#31]
App dont start if put VSCode folder in folder with "#" in name (like "# programs")

**Comment by garethflowers** [comment]
It does the same for me.

I reckon it's a problem with the [PortableApps](https://portableapps.com) launcher the apps using.

**Comment by alekk84** [comment]
I use lot of PortableApps, and they work fine. maybe trouble is in config of launcher?

**Comment by garethflowers** [comment]
I've just tried this again using the [zip file](https://go.microsoft.com/fwlink/?LinkID=623231) provided directly by Visual Studio Code and it does the same thing - so it looks like its an issue with VSCode itself.

Maybe you can log an issue with them - [microsoft/vscode](https://github.com/Microsoft/vscode/issues).
