### ISSUE TITLE
Missing file in archive

### ISSUE THREAD

**Issue by Ghiblifrost** [garethflowers/vscode-portable#34]
Hello, I have been provided your app by a teacher a year ago, and thought it was a really useful to code since it's waaay lighter than the original app and we can use it on anything, which is useful if you have to code on the go. But since then, I my storage device failed and I had to redownload it... Only to find that I couldn't run it because of a missing file as seen below.

![vscode portable missing file](https://user-images.githubusercontent.com/32765532/31540525-2fd356e2-b00c-11e7-9618-b02a7a888d89.PNG)
"Visual Studio Code Portable couldn't start. You could try to reinstall it to solve the problem. (ERROR: App\VSCode64\code.exe not found)"

I hope you can solve this quickly as this app is really important for me and I have a too bad internet provider to download the 17 GB of the main app (if it is even compatible).

Have a good day and keep up th good work.

EDIT: Translated the error message from french to english.

**Comment by garethflowers** [comment]
You can grab the latest copy from the [Releases](https://github.com/garethflowers/vscode-portable/releases) section.

You will probably be best downloading the full zip file (e.g. [VSCodePortable_1.15.1.zip](https://github.com/garethflowers/vscode-portable/releases/download/v1.15.1/VSCodePortable_1.15.1.zip)) as this has everything in it that you will need.

**Comment by Ghiblifrost** [comment]
Oh yeah... I guess I just downloaded the update then... I assumed it was the complete app since I saw the latest release number.

My bad, sorry for wasting your time.

**Comment by nidunc** [comment]
@Ghiblifrost From your comments it seems like you're confusing the full Microsoft Visual Studio program (of which there is a free Community edition, but also paid versions) and Microsoft Visual Studio Code.

Whereas Microsoft Visual Studio (Community, Enterprise, Professional, etc.) is a fully integrated development environment (IDE), which can indeed take up lots of space when you select all options during installation, Microsoft Visual Studio Code is basically a glorified text editor (albeit with code checking and linting for many languages, source control, some debugging options, and many other features which most other text editors don't offer) which takes up around 200MB when freshly installed/extracted - no exceptions. (As of `1.18.0`, the 32-bit `.zip` takes up 177MB and the 64-bit version takes up 206MB.)

Microsoft Visual Studio Code is an official Microsoft product which was probably developed for people who want to code and test code, but don't need the full Visual Studio IDE (which can be quite overkill). VSCode also works on Linux and Mac, which the Visual Studio IDE doesn't.

@garethflowers (the creator of this repository) didn't create this product himself, Microsoft did.
However, what he does in this repository is adapting VSCode to the PortableApps.com format, so it's a truly portable program which can be used on any computer and (ideally) doesn't leave permanent traces.
(By default the `.zip`s you can download from [VSCode's website][vscode] aren't fully portable and place userdata in the user's main and `AppData` directory.)

Here's a quick overview of some differences, hopefully this clears your confusion:

| Product | Microsoft Visual Studio Code | Microsoft Visual Studio IDE |
| --- | --- | --- |
| What is it? | Enhanced text editor | Fully integrated development environment |
| Fresh install size | 200MB, give or take | Anywhere from a few GB to tens of GB's |
| OS | Windows, macOS and Linux distro's | Windows only |
| Price | Free, no paid version | Paid, but there's a free Community version available |


---

Also, there aren't 'update' packages of Visual Studio Code. Every time a new version is released (e.g. from `1.17.1` to `1.18.0`) you basically redownload the full installer or `.zip` archive and overwrite the previous files. This repository doesn't change anything about that - it doesn't offer delta updates (which only include files that were changed between two releases), for example.
The only thing it does is make Visual Studio Code a truly portable program.

[vscode]: https://code.visualstudio.com/ "Visual Studio Code - Code Editing. Redefined"

**Comment by Santhosh114** [comment]
@garethflowers Many thanks to your efforts in bringing the portable VSCode :-) had the same issue and fixed :+1:
