### ISSUE TITLE
VS Code doesn't start

### ISSUE THREAD

**Issue by malaramu** [garethflowers/vscode-portable#35]
When I try to start VS code, code.exe starts running but the programm itself is missing. I've tried this on multiple machines, but the problem remains the same.

**Comment by sergeevabc** [comment]
Windows 7 x64, VSCode 1.16.1

After launching ```VSCodePortable.exe```, all I see is an empty window. @garethflowers, are you there?

![](http://images.vfl.ru/ii/1511370938/413da73f/19529023.png)

**Comment by garethflowers** [comment]
Make sure to download a version of the software from the [Releases](https://github.com/garethflowers/vscode-portable/releases) and not just a copy of the source code.

The [current release is here](https://github.com/garethflowers/vscode-portable/releases/tag/v1.19.0).

**Comment by Henriqueediniz** [comment]
This is my ask too and it worked, tks !
