### ISSUE TITLE
Separate package wanted

### ISSUE THREAD

**Issue by minhducsun2002** [garethflowers/vscode-portable#49]
Can you bundle all within an offline installer, or at least make it a zip that can be extracted to the installation directory? Is it really slow downloading through the installer in some circumstances.

**Comment by garethflowers** [comment]
We used to provide a zip file version of the software - until it was pointed out that the [Visual Studio Code license](https://code.visualstudio.com/License) (from Microsoft) prohibits redistribution.

> You may not
> * share, publish, or lend the software, or provide it as a hosted solution for others to use, or transfer the software or this agreement to any third party.

So we are stuck with the online installer only I'm afraid.

**Comment by minhducsun2002** [comment]
Well, (please consider this as a feature suggestion)
is it possible to make an offline installer that use the official zip file from Microsoft and process it to get the software as if it was downloaded through the online installer?

**Comment by garethflowers** [comment]
Until Microsoft changes their license there is no way we can redistribute their software. Sorry.
