### ISSUE TITLE
Create separate 64bit and 32bit versions

### ISSUE THREAD

**Issue by garethflowers** [garethflowers/vscode-portable#55]
Create both a 32bit and 64bit version.

> The only problem I see is that it downloads both 32 Bit and 64 Bit versions of VS Code.
> It takes a lot of time on slow connections.
> I'd argue 99% of users use 64 Bit version so to the least I'd like to see a 64 Bit version only.

_Originally posted by @RoyiAvital in https://github.com/garethflowers/vscode-portable/issues/53#issuecomment-460402571_

**Comment by RoyiAvital** [comment]
@garethflowers , Any update on this?
Sorry to bug you.

**Comment by RoyiAvital** [comment]
@garethflowers , Any update on this?
Sorry to bug you.

**Comment by garethflowers** [comment]
See release [releases/tag/2.0.0](/garethflowers/vscode-portable/releases/tag/2.0.0)
