### ISSUE TITLE
Can not launch VSCodePortable: App\VSCode\code.exe not found

### ISSUE THREAD

**Issue by riksof-germany** [garethflowers/vscode-portable#6]
You'r app is not working for me, what am I doing wrong? 
FAILURE: App\VSCode\code.exe not found

What about the .zip provided by MS, where is the difference?
https://code.visualstudio.com/Docs/?dv=winzip

**Comment by HammerSquirrel** [comment]
Download the zip from MS and extract it into ./App/VSCode

The documentation for this project says 'download, extract, and run' but that's either inaccurate or out-of-date. If you use the MS download directly it will create artifacts in your user directory, whereas if you use this project to launch the editor those artifacts will end up in the portable directory instead.

**Comment by garethflowers** [comment]
Check [the latest releases section](https://github.com/garethflowers/vscode-portable/releases/latest) for complete downloads. You can download a complete zip file which contains the complete application (i.e. [VSCodePortable_1.3.1.zip](https://github.com/garethflowers/vscode-portable/releases/download/v1.3.1/VSCodePortable_1.3.1.zip))

**Comment by davidtaylorjr** [comment]
I'm having no issues here, works fine. Issue can be closed @garethflowers
