### ISSUE TITLE
Choose custom folder "PlatformIO Core (CLI)"

### ISSUE THREAD

**Issue by stefano972** [garethflowers/vscode-portable#60]
As the title “PlatformIO Core (CLI)” by default is installed in the “C:\Users\ad\AppData\Roaming\SPB_Data”.

To be truly portable I would like to install “PlatformIO Core (CLI)” in a folder of my choice, for example the Visual Studio Code folder.

Thank you for reading this message.

Stefano

**Comment by garethflowers** [comment]
If you are looking to make the PlatformIO Core installation more portable I suggest you checkout their project - https://github.com/platformio/platformio-core.
