### ISSUE TITLE
Disappearing Extension

### ISSUE THREAD

**Issue by wtdmsvp** [garethflowers/vscode-portable#7]
I added an extension folder into Data\vscode\extensions.  When I start VSCodePortable the folder is not copied to <my-profile>\.vscode\extensions and the extension folder under Data\vscode\extensions is gone after I close VSCodePortable.

**Comment by garethflowers** [comment]
Can replicate the issue after opening the portable app `VSCodePortable.exe` multiple times.

It appears as though the `%USERPROFILE\.vscode\extensions` directory is not being cleared out and moved correctly leaving an empty directory behind - which means extensions cannot be restored the next time.

**Comment by garethflowers** [comment]
Fixed by 6a10a1d021af741a62fbf6cbeefd929c77ebbb3d.
